monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            formatter: monolog.formatter.custom_logstash
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.custom_logstash
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
            formatter: monolog.formatter.custom_logstash
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            formatter: monolog.formatter.custom_logstash
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
            formatter: monolog.formatter.custom_logstash
