parameters:
  env(ELASTICSEARCH_HOST): localhost
  env(ELASTICSEARCH_PORT): '9200'
  env(ELASTICSEARCH_TRANSPORT): 'http'
  elasticsearch.host: '%env(ELASTICSEARCH_URL)%'
  elasticsearch.port: '%env(ELASTICSEARCH_PORT)%'
  elasticsearch.transport: '%env(ELASTICSEARCH_TRANSPORT)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Tests\StateController\:
    resource: '../tests/StateController'
    tags: ['controller.service_arguments']
    arguments: [ "@doctrine.orm.entity_manager" ]

  FOS\ElasticaBundle\Finder\FinderInterface:
    alias: fos_elastica.finder.transactions.transaction

  datetime_normalizer:
    class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
    public: false
    tags:
      - { name: serializer.normalizer, priority: 9 }

  Symfony\Component\Serializer\NameConverter\NameConverterInterface: '@serializer.name_converter.camel_case_to_snake_case'

  Symfony\Component\Messenger\MessageBusInterface:
    public: true

  Aws\S3\S3Client:
    autowire: false
    public: true

  Elastica\Client:
    public: true
